### PR TITLE
Adding missing information

### PR DESCRIPTION
**Pull request by Jefe777**
Finishing ordering the information.

@dangowrt Can you check that everything is okay?

### CODE REVIEW

**Comment by mrkiko** [comment]
Well, actually the installer sciprt, and the image containing it is discarded at some point.
In the NAND only the iniramfs recovery remains, if I am right.

**Comment by dangowrt** [comment]
You could also try to write the vendor firmware in case you have only the minimal backup files:
```
mtd -p 0x200000 /dev/mtd3 FW_E8450_1.0.01.101415_prod.img
```

The problem here is that this will only work if there are no bad blocks in the first ~22MB of the SPI-NAND flash as the recovery doesn't support MediaTek's bad block table approach used by the stock firmware.

**Comment by Jefe777** [comment]
@dangowrt I have tried to return with the complete backup 2 times and it works without problem, but I have read that you cannot TFTP with the original firmware and you need a serial console to activate TFTP to flash the vendor firmware. #48

**Comment by Jefe777** [comment]
I have tried to return with the complete backup 2 times and it works without problem, but I have read that you cannot TFTP with the original firmware and you need a serial console to activate TFTP to flash the vendor firmware. #48 

@dangowrt You can add more information if it is missing, if everything is fine you can accept the request or edit what is wrong. 

Thanks.

**Comment by Jefe777** [comment]
I have tried to return with the complete backup 2 times and it works without problem, but I have read that you cannot TFTP with the original firmware and you need a serial console access to activate TFTP to flash the vendor firmware. #48 

@dangowrt You can add more information if it is missing, if everything is fine you can accept the request or edit what is wrong. 

Thanks.

**Comment by Jefe777** [comment]
I have returned to the original firmware with the **complete backup** 2 times (for testing) and it works without problem, but I have read that you cannot use TFTP in the original firmware and you need a serial console to access and activate TFTP in the original/vendor firmware to flash the original/vendor firmware. #48 

@dangowrt If everything is fine you can accept the request or edit what is wrong. 

Thanks.

**Pull request merged**
